---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Create & Start Container
    docker_container:
      name: webserver
      image: "wwm5241/hello:{{ lookup('env','BUILD_NUMBER') }}"
      state: started
      ports:
      - "80:8080"
...
